//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 01:32:16 PM EEST 
//


package com.core.flow.shared.data.dto.application;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;


@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
@AllArgsConstructor
@Builder
public class CustomerApplicationDto {

    private Long applicationID;
    private String customerType;
    private String customerTypeCode;
    private String productType;
    private String productTypeCode;
    private BigDecimal amountToBeFinanced;
    private String date;
    private String loanStatus;
    private String loanStatusCode;
    private String loanReqId;
    private String criteriaName;
}
