//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 01:32:16 PM EEST 
//


package com.core.flow.shared.data.dto.application;

import com.core.flow.shared.data.common.ServiceStatus;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;


@Data
@NoArgsConstructor
@JsonIgnoreProperties
@AllArgsConstructor
@Builder
public class CustomerApplicationsResponse {

    private ServiceStatus serviceStatus;
    private long count;
    private int totalPage;
    private List<CustomerApplicationDto> pageList = new ArrayList<>();


}
